add-enum-types = true
no-tests = true
output = "./store/models/"
wipe = true

[psql]
dbname = "api"
host = "localhost"
port = "5432"
user = "api"
pass = "api"
sslmode = "disable"
blacklist = ["schema_migrations"]


